<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHBMpCU8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHBMpCU8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHBMpCU8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHBMpCU8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHBMpCU8\App_KernelDevDebugContainer([
    'container.build_hash' => 'HBMpCU8',
    'container.build_id' => 'e329a99f',
    'container.build_time' => 1632233877,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHBMpCU8');
